### ISSUE TITLE
Allow OR searches with a comma

### ISSUE THREAD

**Issue by stropitek** [cheminfo/smart-array-filter#30]
For example:

```
Roche,"Ciba geigy",Lonza
company:Roche,Novartis
company:Roche,"Ciba geigy"
location:"Paris, France","London, UK"
```

**Comment by stropitek** [comment]
Ref: https://github.com/cheminfo/smart-array-filter/commit/8652f11d752ca2ddb79d71cab893df3f40aaba6e

@lpatiny I don't see any tests where one of the value has a space. Could you add one / implement this in the parser if it does not work yet?

**Comment by lpatiny** [comment]
Because those examples do not work ... I will check.

**Comment by lpatiny** [comment]
Closed by https://github.com/cheminfo/smart-array-filter/commit/2798d82f38170c034e2c65b5abe805587c054790
